name: "ALE/MsPacman-v5"
gym_backend: "gymnasium"
gym_env_kwargs:
  frame_skip: 4
  from_pixels: true
  pixels_only: true
  categorical_action_space: true

transforms:
  -_target_: torchrl.envs.NoopResetEnv
    noops:30
    random: True
  -_target_: torchrl.envs.EndOfLifeTransform
  -_target_: torchrl.envs.SignTransform
    in_keys: ["reward"]
  -_target_: torchrl.encs.ToTensorImage
  -_target_: torchrl.envs.RewardSum
  -_target_: torchrl.envs.StepCounter
    max_steps: 4500
  -_target_: torchrl.envs.DoubleToFloat